
import numpy as np
from collections import OrderedDict
import glob
import pandas as pd
import os
import shutil
import re
import glob
from pymatgen.io.ase import AseAtomsAdaptor
from pymatgen.io.cif import CifWriter
from ase import Atoms
from ase.visualize import view

def read_xyz(name):
    "read xyz data generated from ocito or python."
    with open(name,'r') as file1:
        fileline=file1.readlines()[2:]
    data = []
    ele_num = []
    for line in fileline:
            value=line.split()[1:]
            ele=line.split()[0]
            data.append([np.double(value[0]),np.double(value[1]),np.double(value[2])])
            ele_num.append(ele)
    return ele_num, np.array(data)

def write_xyz(fileobj, images, comment='', fmt='%22.15f'):
    comment = comment.rstrip()
    if '\n' in comment:
        raise ValueError('Comment line should not have line breaks.')

    natoms = len(images)
    fileobj.write('%d\n%s\n' % (natoms, comment))
    for s, (x, y, z) in zip(images.symbols, images.positions):
        fileobj.write('%-2s %s %s %s\n' % (s, fmt % x, fmt % y, fmt % z))


def sort_filename(filename_partten):
    "sort xyz files generated by lammps and ovito"
    xyz_files=glob.glob(filename_partten)
    sort_file=dict()
    for i in range(0,len(xyz_files)):
        sort_file[int(xyz_files[i].split('.')[0].split('_')[1])]=xyz_files[i]
    files=[]
    for i in sorted(sort_file.keys()):
        files.append(sort_file[i])
    return files


def dir_list(dir):
    """
    only show subdirectories
    :param dir:
    :return: dirlist
    """
    dirlist = []
    for it in os.scandir(dir):
        if it.is_dir():
            dirlist.append(it.path)
    return dirlist

def dir_create(name):
    """
    Create file
    :param name:file name
    :return: no return
    """
    if not os.path.isdir(name):
        os.mkdir(name)

def dir_create_deltree(parent_dir,outfoldername):
    directory = outfoldername
    path = os.path.join(parent_dir, directory)
    if os.path.isdir(path):
        del_dir(path)
        print("Directory %s is already existed." %directory)
    else:
        os.makedirs(path)
        print("Directory %s created" %directory)
    return path

def del_dir(name):
    """
    copy from stackoverflow
    delete all files in a dir, not delete dir., and only can work if directory containss multiple directories
    :param name: directory
    :return: no return
    """
    for files in os.listdir(name):
        path = os.path.join(name, files) # get file names in the dir
        try:
            if os.path.isfile(path) or os.path.islink(path):
                os.unlink(path)
            elif os.path.isdir(path):
                shutil.rmtree(path)  #delete all files
        except Exception as e:
            print('Failed to delete %s. Reason: %s' % (path, e)) # don't show the message
            #print("The directory is empty!") #print the empty state of files


def writing_xyz(coords,atom_type,path,n=1) :
    """
    the goal of writing_xyz is to write xyz file according to the positions of
    atoms from a cluster.
    :param coords: positions of atoms
    :param atom_type: atom type: eg:'Pt','Cu','Ni'
    :param n: the index of file in the file list (sometimes, we need to generate many files of same
               shapes, for example: different sizes of particles of same shape.)
    :param path: the directory name (indicate the shape of particles)
    :param name: name of file. In this case particle shape.
    """
    c = list(coords)
    #if not os.path.isfile(path):
    #    makedir(path)
    with open(path+'/'+path+str(n)+".xyz",'w') as file1:
        file1.write(str(len(c))+'\n')
        file1.write(str('0 '+'0 '+'0 ')+str('\n'))
        for i in range(len(c)):
            strr = atom_type + str(" ")+str(c[i][0])+str(" ")+str(c[i][1])+str(" ")+str(c[i][2])+str("\n")
            file1.write(strr)

        
def atom2pymat_cif(atoms,filename):
    """
    Convert ase atoms object to pymatgen structure object and write to cif file

    Args:
        atoms (ase.Atoms): ase atoms object
        filename (str): filename for cif file:
        eg: filename="task1_distorted_structures//KMgCl3_"+str(k)+".cif"
    """
    structure=AseAtomsAdaptor.get_structure(atoms)
    CifWriter(structure).write_file(filename)   
def read_xyz2atoms(filename,viewer='ase',plot=True)->Atoms:
    """
    Note: cannot use x3d viewer in jupyter notebook
    """
    atom_txt=read_xyz(filename)
    atoms=Atoms(positions=atom_txt[1],symbols=atom_txt[0])
    if plot==True:
        view(atoms,viewer=viewer)
    return atoms